# Generated by Django 4.0.3 on 2022-04-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministracionBlog', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appAdministracionBlog.usuario'),
        ),
    ]
